### ISSUE TITLE
Why goofys could NOT list Non root directories correctly

### ISSUE THREAD

**Issue by silenceli** [kahing/goofys#333]
# Environment
goofys running in docker, compiled from source, commit id: b2302fdf5af978f1698c0b21f38f01928da25b2f
go: go version go1.10.2 linux/amd64
OS: CentOS Linux release 7.2.1511 (Core)

# Problem description

We can see all files in root directories:
![goofys_ls_root_directories](https://user-images.githubusercontent.com/1579708/41890257-503aba84-7941-11e8-9891-4d2839b34885.png)

We can't see files but only directories in tmp directory:
![goofys_ls_non_root_directories](https://user-images.githubusercontent.com/1579708/41890256-4ff86134-7941-11e8-9db1-aeceb58094f8.png)

But, use s3cmd, tmp directory contains a log of files:
![s3md_can_show_files_in_tmp_directory](https://user-images.githubusercontent.com/1579708/41890260-50764d9c-7941-11e8-82d9-d89a6605bbd0.png)

Hope for your reply soon.

**Comment by lnicola** [comment]
@silenceli I've seen the same issue on bb740f10dcac02ddb3a859c4b7c3d9d22849af5a, while 6b55674433a801daef71168405f1625455aa361b worked for me; can you check the in-between versions? I suspect https://github.com/kahing/goofys/commit/2e8ba3adb4f58bc0c977e53ab859c145fae3220e caused this.

**Comment by kahing** [comment]
Could one of you describe exactly how to reproduce this?

**Comment by lnicola** [comment]
I don't know what caused this, but it's fixed by https://github.com/kahing/goofys/commit/be26037cebcf83bb972ecede1c3c9f888f107580.

I tested with an OpenStack container/bucket. My files don't have special characters in their names:

```
# bad
$ sudo mount /mnt/C02; ll /mnt/C02/romania/l2a/S2B_MSIL2A_20171227T091359_N0206_R050_T35TNK_20171227T115119.SAFE/S2B_OPER_SSC_L2VALD_35TNK____20171227.DBL.DIR; sudo umount /mnt/C02
total 4.0K
drwxr-xr-x 2 grayshade grayshade 4.0K Jul  9 13:49 PRIVATE
# good
$ sudo mount /mnt/C02; ll /mnt/C02/romania/l2a/S2B_MSIL2A_20171227T091359_N0206_R050_T35TNK_20171227T115119.SAFE/S2B_OPER_SSC_L2VALD_35TNK____20171227.DBL.DIR; sudo umount /mnt/C02
total 2.3G
drwxr-xr-x 2 grayshade grayshade 4.0K Jul  9 13:50 PRIVATE
-rw-r--r-- 1 grayshade grayshade 231M May 27 11:55 S2B_OPER_SSC_PDTANX_L2VALD_35TNK____20171227_ATB_R1.DBL.TIF
-rw-r--r-- 1 grayshade grayshade 3.0K May 27 11:55 S2B_OPER_SSC_PDTANX_L2VALD_35TNK____20171227_ATB_R1.HDR
-rw-r--r-- 1 grayshade grayshade  58M May 27 11:55 S2B_OPER_SSC_PDTANX_L2VALD_35TNK____20171227_ATB_R2.DBL.TIF
-rw-r--r-- 1 grayshade grayshade 3.0K May 27 11:55 S2B_OPER_SSC_PDTANX_L2VALD_35TNK____20171227_ATB_R2.HDR
-rw-r--r-- 1 grayshade grayshade 116M May 27 11:55 S2B_OPER_SSC_PDTANX_L2VALD_35TNK____20171227_CLD_R1.DBL.TIF
-rw-r--r-- 1 grayshade grayshade 2.8K May 27 11:55 S2B_OPER_SSC_PDTANX_L2VALD_35TNK____20171227_CLD_R1.HDR
-rw-r--r-- 1 grayshade grayshade  29M May 27 11:55 S2B_OPER_SSC_PDTANX_L2VALD_35TNK____20171227_CLD_R2.DBL.TIF
-rw-r--r-- 1 grayshade grayshade 2.8K May 27 11:55 S2B_OPER_SSC_PDTANX_L2VALD_35TNK____20171227_CLD_R2.HDR
-rw-r--r-- 1 grayshade grayshade 116M May 27 11:55 S2B_OPER_SSC_PDTANX_L2VALD_35TNK____20171227_MSK_R1.DBL.TIF
-rw-r--r-- 1 grayshade grayshade 2.8K May 27 11:55 S2B_OPER_SSC_PDTANX_L2VALD_35TNK____20171227_MSK_R1.HDR
-rw-r--r-- 1 grayshade grayshade  29M May 27 11:55 S2B_OPER_SSC_PDTANX_L2VALD_35TNK____20171227_MSK_R2.DBL.TIF
-rw-r--r-- 1 grayshade grayshade 2.8K May 27 11:55 S2B_OPER_SSC_PDTANX_L2VALD_35TNK____20171227_MSK_R2.HDR
-rw-r--r-- 1 grayshade grayshade 346M May 27 11:55 S2B_OPER_SSC_PDTANX_L2VALD_35TNK____20171227_QLT_R1.DBL.TIF
-rw-r--r-- 1 grayshade grayshade 2.9K May 27 11:55 S2B_OPER_SSC_PDTANX_L2VALD_35TNK____20171227_QLT_R1.HDR
-rw-r--r-- 1 grayshade grayshade  87M May 27 11:55 S2B_OPER_SSC_PDTANX_L2VALD_35TNK____20171227_QLT_R2.DBL.TIF
-rw-r--r-- 1 grayshade grayshade 2.9K May 27 11:55 S2B_OPER_SSC_PDTANX_L2VALD_35TNK____20171227_QLT_R2.HDR
-rw-r--r-- 1 grayshade grayshade 920M May 27 11:56 S2B_OPER_SSC_PDTIMG_L2VALD_35TNK____20171227_FRE_R1.DBL.TIF
-rw-r--r-- 1 grayshade grayshade 2.6K May 27 11:56 S2B_OPER_SSC_PDTIMG_L2VALD_35TNK____20171227_FRE_R1.HDR
-rw-r--r-- 1 grayshade grayshade 345M May 27 11:56 S2B_OPER_SSC_PDTIMG_L2VALD_35TNK____20171227_FRE_R2.DBL.TIF
-rw-r--r-- 1 grayshade grayshade 2.7K May 27 11:56 S2B_OPER_SSC_PDTIMG_L2VALD_35TNK____20171227_FRE_R2.HDR
-rw-r--r-- 1 grayshade grayshade  88K May 27 11:56 S2B_OPER_SSC_PDTQLK_L2VALD_35TNK____20171227.DBL.JPG
-rw-r--r-- 1 grayshade grayshade 2.7K May 27 11:56 S2B_OPER_SSC_PDTQLK_L2VALD_35TNK____20171227.HDR
```

**Comment by lnicola** [comment]
```
# bad
touch /mnt/C02/test/S2B; ll /mnt/C02/test; sudo umount /mnt/C02; sudo mount /mnt/C02; ll /mnt/C02/test 
total 4.0K
drwxr-xr-x 2 grayshade grayshade 4.0K Jul  9 14:04 S2B_MSIL2A_20171227T091359_N0206_R050_T35TNK_20171227T115119.SAFE
-rw-r--r-- 1 grayshade grayshade    0 Jul  9 14:04 S2B
# this one is older
-rw-r--r-- 1 grayshade grayshade    0 Jul  9 14:04 S2B_OPER
total 4.0K
drwxr-xr-x 2 grayshade grayshade 4.0K Jul  9 14:04 S2B_MSIL2A_20171227T091359_N0206_R050_T35TNK_20171227T115119.SAFE
```

I still don't know what caused this.

**Comment by silenceli** [comment]
@lnicola I have tried commit id: bb740f10dcac02ddb3a859c4b7c3d9d22849af5a. This commit is OK for me.

I also still don't know what cause my problem.

**Comment by silenceli** [comment]
@lnicola I suspect b2302fdf5af978f1698c0b21f38f01928da25b2f caused this.

**Comment by lnicola** [comment]
@silenceli I know, and that commit was reverted, fixing the issue.

But my files don't have special characters in their name, which is what I meant by not knowing what caused this.
